# Generated by Django 5.2.8 on 2025-11-12 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe collection identifier (e.g., 'myproject' becomes /myproject/)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this collection", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="MockEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name for this endpoint", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "path",
                    models.CharField(
                        help_text="Path after collection (e.g., 'users' becomes /{collection}/users)",
                        max_length=500,
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        default="GET",
                        max_length=10,
                    ),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        choices=[
                            (200, "200 - OK"),
                            (201, "201 - Created"),
                            (202, "202 - Accepted"),
                            (204, "204 - No Content"),
                            (400, "400 - Bad Request"),
                            (401, "401 - Unauthorized"),
                            (403, "403 - Forbidden"),
                            (404, "404 - Not Found"),
                            (405, "405 - Method Not Allowed"),
                            (409, "409 - Conflict"),
                            (422, "422 - Unprocessable Entity"),
                            (429, "429 - Too Many Requests"),
                            (500, "500 - Internal Server Error"),
                            (502, "502 - Bad Gateway"),
                            (503, "503 - Service Unavailable"),
                            (504, "504 - Gateway Timeout"),
                        ],
                        default=200,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("application/json", "application/json"),
                            ("application/xml", "application/xml"),
                            ("text/plain", "text/plain"),
                            ("text/html", "text/html"),
                            (
                                "application/x-www-form-urlencoded",
                                "application/x-www-form-urlencoded",
                            ),
                        ],
                        default="application/json",
                        max_length=100,
                    ),
                ),
                (
                    "content_encoding",
                    models.CharField(
                        blank=True, help_text="Content-Encoding header", max_length=50
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        default='{"msg": "Hello World"}',
                        help_text="Response body (JSON, XML, text, etc.)",
                    ),
                ),
                (
                    "custom_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom headers as key-value pairs (e.g., {'X-Custom-Header': 'value'})",
                    ),
                ),
                (
                    "enable_dynamic_response",
                    models.BooleanField(
                        default=False,
                        help_text="Enable dynamic templating (future feature)",
                    ),
                ),
                (
                    "enable_request_logger",
                    models.BooleanField(
                        default=True, help_text="Log requests to this endpoint"
                    ),
                ),
                (
                    "response_delay",
                    models.IntegerField(
                        default=0, help_text="Response delay in seconds"
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0, help_text="Order position in collection"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="domains.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock Endpoint",
                "verbose_name_plural": "Mock Endpoints",
                "ordering": ["position", "path"],
                "unique_together": {("collection", "path", "http_method")},
            },
        ),
    ]
