# Generated by Django 5.2.8 on 2025-11-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndpointResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Response name (e.g., Success, Error)", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "response_status",
                    models.IntegerField(
                        choices=[
                            (200, "200 - OK"),
                            (201, "201 - Created"),
                            (202, "202 - Accepted"),
                            (204, "204 - No Content"),
                            (400, "400 - Bad Request"),
                            (401, "401 - Unauthorized"),
                            (403, "403 - Forbidden"),
                            (404, "404 - Not Found"),
                            (405, "405 - Method Not Allowed"),
                            (409, "409 - Conflict"),
                            (422, "422 - Unprocessable Entity"),
                            (429, "429 - Too Many Requests"),
                            (500, "500 - Internal Server Error"),
                            (502, "502 - Bad Gateway"),
                            (503, "503 - Service Unavailable"),
                            (504, "504 - Gateway Timeout"),
                        ],
                        default=200,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("application/json", "application/json"),
                            ("application/xml", "application/xml"),
                            ("text/plain", "text/plain"),
                            ("text/html", "text/html"),
                            (
                                "application/x-www-form-urlencoded",
                                "application/x-www-form-urlencoded",
                            ),
                        ],
                        default="application/json",
                        max_length=100,
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        default='{"message": "Success"}', help_text="Response body"
                    ),
                ),
                (
                    "custom_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom headers for this response",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use this as the default response"
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="domains.mockendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endpoint Response",
                "verbose_name_plural": "Endpoint Responses",
                "ordering": ["position", "created_at"],
            },
        ),
    ]
