# Generated by Django 5.2.8 on 2025-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0002_endpointresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="openapi_schema",
            field=models.TextField(
                blank=True, help_text="Custom OpenAPI YAML schema for this collection"
            ),
        ),
    ]
